#1주차 과제
- 파이토치 시작하기 및 간단한 코드 빈칸 채워넣기

#파이토치 시작하기

파이토치 시작하기

In [ ]:
import torch 

- tensor 개념 파악 (array of numerical values(vector, matrix..))
- 4x3 행렬 두개 만들고 행으로 병합, 열로 병합


In [ ]:
X=torch.randn(4,3)
Y=torch.randn(4,3)
###행으로 병합 코드
print(torch.cat([X,Y],dim=1))
###열로 병합 코드
print(torch.cat([X,Y],dim=0))

tensor([[ 0.4875,  0.0788,  0.1097,  0.6240, -1.6170, -1.0634],
        [ 0.4532,  0.4348,  2.1657,  0.9123,  1.2116,  1.2013],
        [-1.2561, -0.3008, -1.2852, -1.8491,  0.2709, -0.2938],
        [-2.8118, -1.1775,  1.1240, -0.2988,  1.4373,  0.7715]])
tensor([[ 0.4875,  0.0788,  0.1097],
        [ 0.4532,  0.4348,  2.1657],
        [-1.2561, -0.3008, -1.2852],
        [-2.8118, -1.1775,  1.1240],
        [ 0.6240, -1.6170, -1.0634],
        [ 0.9123,  1.2116,  1.2013],
        [-1.8491,  0.2709, -0.2938],
        [-0.2988,  1.4373,  0.7715]])


linear regression implementation from scratch
- 머신러닝 기초와 비슷한 내용이지만 파이토치로 실행해보며 익숙해지는것이 목표


In [ ]:
!pip install d2l

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.6/112.6 KB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 31.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 88.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 57.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.0/121.0 KB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 965.4/965.4 KB 57.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.6/83.6 KB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 72.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:

In [ ]:
!pip install --upgrade ipykernel

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 775.8/775.8 KB 23.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 424.0/424.0 KB 36.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.4/386.4 KB 33.5 MB/s eta 0:00:00
  Attempting uninstall: tornado
    Found existing installation: tornado 6.0.4
    Uninstalling tornado-6.0.4:
      Successfully uninstalled tornado-6.0.4
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 2.0.10
    Uninstalling prompt-toolkit-2.0.10:
      Successfully uninstalled prompt-toolkit-2.0.10
  Attempting uninstall: ipython
    Found existing installation: ipython 7.9.0
    Uninstalling ipython-7.9.0:
      Successfully uninstalled ipython-7.9.0
  Attempting uninstall: ipykernel
    Found existing installation: ipykernel 5

In [ ]:
%matplotlib inline
import random
import torch
from d2l import torch as d2l

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [ ]:
def synthetic_data(w, b, num_examples):
    """Generate y = Xw + b + noise."""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = synthetic_data(true_w, true_b, 2000)

In [ ]:
print('features:', features[0],'\nlabel:', labels[0])

features: tensor([-1.6653,  0.7284]) 
label: tensor([-0.5983])


In [ ]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # The examples are read at random, in no particular order
    random.shuffle(indices)
     ###반복문으로 채워넣기:
    for i in range(0, num_examples, batch_size):
        ##이하는 반복문에 대한 조건입니다.
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [ ]:
batch_size = 20

for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

tensor([[-1.6549, -0.8981],
        [-1.3252,  0.3461],
        [ 0.0622,  0.2560],
        [-0.3991, -0.7965],
        [-0.4647, -1.1888],
        [-0.5672, -0.4126],
        [-0.0513,  0.5529],
        [-1.9270,  0.4840],
        [-0.9263, -0.6237],
        [ 0.8779,  1.5761],
        [ 0.7797,  0.5842],
        [ 0.5159, -0.4578],
        [ 0.0163, -0.7625],
        [-1.3756,  1.9322],
        [ 0.4395,  1.6709],
        [-0.4794, -0.3935],
        [ 0.1562, -0.9291],
        [ 3.0943,  0.2821],
        [ 0.8552,  0.9645],
        [-0.5753, -1.2172]]) 
 tensor([[ 1.8902],
        [ 1.0048],
        [ 5.3012],
        [ 5.4864],
        [ 5.8813],
        [ 4.4137],
        [ 4.5077],
        [-1.0013],
        [ 3.6575],
        [ 5.7557],
        [ 6.9510],
        [ 7.7403],
        [ 6.7041],
        [-1.5205],
        [ 4.3183],
        [ 4.6649],
        [ 7.3591],
        [14.3640],
        [ 6.6040],
        [ 5.6171]])


In [ ]:
w = torch.normal(0, 0.01, size=(2,1), requires_grad=True)
b = torch.tensor([2])#원하는 실수를 넣어주세요

In [ ]:
def linreg(X, w, b):
    """The linear regression model."""
    return torch.matmul(X,w)+b ###lr func 코드 완성하기

In [ ]:
def squared_loss(y_hat, y):  
    """Squared loss."""
    return (y_hat - y.reshape(y_hat.shape)) ** 2 / 2 ###loss function 직접 짜보기

In [ ]:
def sgd(params, lr, batch_size):
    """Minibatch stochastic gradient descent."""
    with torch.no_grad():
        ###반복문으로 채워넣기
      for param in params:
          param -= lr * param.grad / batch_size
          return param.grad.zero_()  

In [ ]:
lr = 0.05 ###직접 설정
num_epochs = 3 ###직접 설정
net = linreg ###위에서 가져오기
loss = squared_loss ###위에서 가져오기

for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):
        l = loss(net(X,w,b), y) 
        # Compute gradient on `l` with respect to [`w`, `b`]
        l.sum().backward()
        sgd([w,b], lr, batch_size) 
    with torch.no_grad():
        train_l = loss(net(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')

epoch 1, loss 6.119224
epoch 2, loss 6.122610
epoch 3, loss 6.128119


In [ ]:
print(f'error in estimating w: {true_w - w.reshape(true_w.shape)}')
print(f'error in estimating b: {true_b - b}')

error in estimating w: tensor([0.0924, 0.1137], grad_fn=<SubBackward0>)
error in estimating b: tensor([3.5000])


+cost graph 그리기 (x축 w, y축 loss)

In [ ]:
import matplotlib.pyplot as plt

w_list=[]
loss_list=[]

for i in range(-30,50):
  l = squared_loss(linreg(X,w,b), y) 
  w_list.append(w)
  loss_list.append(l.mean())

plt.plot(w_list, loss_list)
plt.xlabel('w')
plt.ylabel('loss')
plt.show()

concise implementation of linear regression 
- api 사용해보기

In [ ]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l


true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = d2l.synthetic_data(true_w, true_b, 2000)

In [ ]:
def load_array(data_arrays, batch_size, is_train=True): 
    """Construct a PyTorch data iterator."""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 20
data_iter = load_array((features, labels), batch_size)

In [ ]:
next(iter(data_iter))

[tensor([[ 0.9948, -1.2078],
         [ 1.5183, -1.8640],
         [-1.6798,  1.4835],
         [-0.1576, -0.4585],
         [-1.1623, -0.0077],
         [ 1.1000,  0.1353],
         [ 0.4716,  0.6517],
         [-0.1779,  0.1686],
         [-1.1996,  1.2126],
         [ 0.2597,  1.4427],
         [ 2.1897,  0.6725],
         [-0.5792,  1.5360],
         [ 0.4650, -0.8077],
         [-1.0692,  1.6908],
         [-1.0951,  0.2122],
         [ 2.0923,  1.9617],
         [ 0.8816,  0.0911],
         [ 0.5655,  2.2004],
         [ 0.0144,  0.2430],
         [-0.6292, -0.7597]]), tensor([[10.3088],
         [12.8398],
         [-1.7582],
         [ 5.7084],
         [ 2.0326],
         [ 8.5957],
         [ 5.9324],
         [ 4.7167],
         [ 0.0717],
         [ 4.1175],
         [11.0496],
         [ 1.4701],
         [ 8.1261],
         [-0.2347],
         [ 1.9064],
         [ 8.8262],
         [ 8.0262],
         [ 3.9128],
         [ 5.1861],
         [ 4.7609]])]

In [ ]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))###채워넣기

In [ ]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [ ]:
loss =nn.MSELoss() ###api function으로 직접 설정

In [ ]:
trainer =torch.optim.SGD(net.parameters(), lr=0.03) ###api function으로 직접 설정

In [ ]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X),y) ###직접설정
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000221
epoch 2, loss 0.000099
epoch 3, loss 0.000099


In [ ]:
w = net[0].weight.data ###학습결과 w 구하는 식
print('error in estimating w:', true_w - w.reshape(true_w.shape))
b = net[0].bias.data ###학습결과 b 구하는 식
print('error in estimating b:', true_b - b)

error in estimating w: tensor([-8.9407e-05, -4.0603e-04])
error in estimating b: tensor([0.0005])
