#1주차 과제
- 파이토치 시작하기 및 간단한 코드 빈칸 채워넣기

#파이토치 시작하기

파이토치 시작하기

In [1]:
import torch 

- tensor 개념 파악 (array of numerical values(vector, matrix..))
- 4x3 행렬 두개 만들고 행으로 병합, 열로 병합


In [2]:
X = torch.ones((4,3))
Y = torch.zeros((4,3))

###행으로 병합 코드
torch.cat((X,Y), dim = 0)

###열로 병합 코드
torch.cat((X,Y), dim = 1)




tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

linear regression implementation from scratch
- 머신러닝 기초와 비슷한 내용이지만 파이토치로 실행해보며 익숙해지는것이 목표


In [3]:
# !pip install d2l

In [4]:
import matplotlib.pyplot as plt
# %matplotlib inline
import random
import torch
from d2l import torch as d2l
import math

In [5]:
def synthetic_data(w, b, num_examples):
    """Generate y = Xw + b + noise."""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = synthetic_data(true_w, true_b, 2000)

In [6]:
print('features:', features[0],'\nlabel:', labels[0])

features: tensor([-0.4943,  0.0110]) 
label: tensor([3.9953])


In [7]:
batch_size = 2

In [8]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # The examples are read at random, in no particular order
    random.shuffle(indices)
     ###반복문으로 채워넣기:
        ##이하는 반복문에 대한 조건입니다.
    for i in range(math.ceil(num_examples / batch_size)):
        batch_indices = torch.tensor(indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [9]:
for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

tensor([[ 0.4020, -0.0354],
        [ 1.5937, -0.7750]]) 
 tensor([[ 6.7650],
        [11.4407]])


In [10]:
w = torch.normal(0, 0.01, size=(2,1), requires_grad=True)
b = torch.Tensor(3 )#원하는 실수를 넣어주세요


In [11]:
def linreg(X, w, b):
    """The linear regression model."""
    y = torch.matmul(X, w) + b
    return y
     ###lr func 코드 완성하기

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Using a target size (torch.Size([2, 1])) that is different to the input size (torch.Size([2, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  This is separate from the ipykernel package so we can avoid doing imports until


tensor(inf, grad_fn=<MseLossBackward0>)

In [76]:
def squared_loss(y_hat, y):  
    """Squared loss."""
    diff = torch.sqrt((y_hat - y) ** 2)
    return diff###loss function 직접 짜보기

In [77]:
# def sgd(params, lr, batch_size):
#     """Minibatch stochastic gradient descent."""

#     with torch.no_grad():
#         for idx in range(batch_size):
           
#             part = torch.zeros(params.shape)

#             params = params - 2 * lr * l * 1
            
            


#     return loss(net(X, w, b), y)

#         ###반복문으로 채워넣기

In [78]:
from copy import deepcopy
net = deepcopy(linreg)
w = torch.normal(0, 0.01, size=(2,1), requires_grad=True)
b = torch.Tensor(3 )#원하는 실수를 넣어주세요a
b.requires_grad_(True)

z = net(X, w, b)

batch_size = 2
lr = 0.01
num_epochs = 100



loss_fun = squared_loss
loss = loss_fun(net(X, w, b), y)
loss.sum().backward()

In [79]:
from copy import deepcopy
import tqdm






for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):

        w = w - lr * w.grad
        b = b - lr * b.grad
        w.detach_().requires_grad_(True)
        b.detach_().requires_grad_(True)

        z = net(X, w, b)
        loss = loss_fun(z, y)
        # Compute gradient on `l` with respect to [`w`, `b`]
        loss.mean().backward()


    with torch.no_grad():

        train_l = loss_fun(net(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')

epoch 1, loss inf
epoch 2, loss inf
epoch 3, loss inf
epoch 4, loss inf
epoch 5, loss inf
epoch 6, loss inf
epoch 7, loss inf
epoch 8, loss inf
epoch 9, loss inf
epoch 10, loss inf
epoch 11, loss inf


KeyboardInterrupt: 

In [ ]:
print(f'error in estimating w: {true_w - w.reshape(true_w.shape)}')
print(f'error in estimating b: {true_b - b}')

+cost graph 그리기 (x축 w, y축 loss)

concise implementation of linear regression 
- api 사용해보기

In [145]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l


true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = d2l.synthetic_data(true_w, true_b, 2000)

In [146]:
def load_array(data_arrays, batch_size, is_train=True): 
    """Construct a PyTorch data iterator."""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 20
data_iter = load_array((features, labels), batch_size)

In [147]:
next(iter(data_iter))

[tensor([[-1.4734,  0.6347],
         [-1.5959, -1.4912],
         [ 1.0237,  2.4512],
         [ 0.2395,  0.3285],
         [-0.6422,  0.1363],
         [-1.2340, -0.9216],
         [ 0.7048, -0.3399],
         [ 1.8234,  1.1751],
         [ 2.1104,  0.0038],
         [-0.0412, -0.6555],
         [-1.0069,  0.4127],
         [ 2.5950, -0.4650],
         [ 0.8614, -0.9055],
         [-0.0716, -0.0112],
         [-1.5657,  0.6340],
         [ 2.2878,  1.1505],
         [-0.7395, -0.5672],
         [ 0.1311,  1.4754],
         [ 0.5626,  1.0101],
         [ 1.4147,  0.7226]]),
 tensor([[ 0.1164],
         [ 2.9502],
         [ 4.8995],
         [ 5.7190],
         [ 3.3681],
         [ 3.1845],
         [ 8.1150],
         [ 9.2027],
         [11.8098],
         [ 6.3682],
         [ 1.8595],
         [13.9746],
         [ 9.4610],
         [ 5.3027],
         [-0.1471],
         [10.6279],
         [ 4.1184],
         [ 3.6828],
         [ 5.6718],
         [ 8.6709]])]

In [148]:
features.shape

torch.Size([2000, 2])

In [149]:
labels.dim()

2

In [150]:
from torch import nn

net = nn.Sequential( nn.Linear(in_features=features.dim(), out_features=labels.dim()))

In [151]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0., 0.])

In [152]:
import torch.nn.functional as F

#api function으로 직접 설정

loss_fun = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(), lr =0.01)###api function으로 직접 설정

In [155]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:

        l = loss_fun(X,y)
        trainer.zero_grad()
        l.requires_grad_(True)
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 42.081650
epoch 2, loss 42.081650
epoch 3, loss 42.081650


C:\Users\USER\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([2000, 1])) that is different to the input size (torch.Size([2000, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [156]:
w = ###학습결과 w 구하는 식
print('error in estimating w:', true_w - w.reshape(true_w.shape))
b = ###학습결과 b 구하는 식
print('error in estimating b:', true_b - b)

SyntaxError: invalid syntax (<ipython-input-156-d922e4f64034>, line 1)