#1주차 과제
- 파이토치 시작하기 및 간단한 코드 빈칸 채워넣기

#파이토치 시작하기

파이토치 시작하기

In [65]:
import torch 

- tensor 개념 파악 (array of numerical values(vector, matrix..))
- 4x3 행렬 두개 만들고 행으로 병합, 열로 병합


In [66]:
X=torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])###
Y=torch.tensor([[3,2,1],[6,5,4],[9,8,7],[12,11,10]])###
###행으로 병합 코드
output1 = torch.cat([X,Y], dim=1)
###열로 병합 코드
output2 = torch.cat([X,Y], dim=0)
print(output1)
print(output2)

tensor([[ 1,  2,  3,  3,  2,  1],
        [ 4,  5,  6,  6,  5,  4],
        [ 7,  8,  9,  9,  8,  7],
        [10, 11, 12, 12, 11, 10]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [ 3,  2,  1],
        [ 6,  5,  4],
        [ 9,  8,  7],
        [12, 11, 10]])


linear regression implementation from scratch
- 머신러닝 기초와 비슷한 내용이지만 파이토치로 실행해보며 익숙해지는것이 목표


In [67]:
!pip install d2l

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [68]:
!pip install matplotlib_inline

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [69]:
%matplotlib inline


In [70]:
import random
import torch
from d2l import torch as d2l

In [95]:
def synthetic_data(w, b, num_examples):
    """Generate y = Xw + b + noise."""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = synthetic_data(true_w, true_b, 2000)

In [72]:
print('features:', features[0],'\nlabel:', labels[0])

features: tensor([-0.4644,  0.6508]) 
label: tensor([3.1355])


In [73]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # The examples are read at random, in no particular order
    random.shuffle(indices)
     ###반복문으로 채워넣기:
    for i in range(0,num_examples,batch_size):
        ##이하는 반복문에 대한 조건입니다.
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [74]:
batch_size = 20

for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)
    break

tensor([[ 0.5267,  1.0216],
        [ 0.0917, -0.2706],
        [ 0.1949,  2.2944],
        [ 0.7318, -0.5958],
        [ 0.2291, -0.2680],
        [ 0.2417, -1.5469],
        [ 0.2698, -1.1942],
        [ 0.5967, -0.3464],
        [ 1.0833,  0.7163],
        [-0.9125, -1.0956],
        [-1.0810,  1.1647],
        [ 0.8005,  0.9334],
        [ 1.0398,  0.6776],
        [ 0.5096, -0.7914],
        [-1.2305,  0.5370],
        [-0.6155,  0.5317],
        [-0.0543,  0.2252],
        [-1.2415, -1.0919],
        [ 0.0925, -0.7764],
        [-1.4170,  0.2191]]) 
 tensor([[5.5450],
        [6.1754],
        [2.6418],
        [8.5891],
        [6.5821],
        [8.5502],
        [8.0857],
        [7.8086],
        [7.6687],
        [4.4144],
        [0.5114],
        [6.5089],
        [7.6117],
        [8.2100],
        [1.0013],
        [2.8546],
        [5.0135],
        [3.4156],
        [6.9489],
        [0.9170]])


In [75]:
w = torch.normal(0, 0.01, size=(2,1), requires_grad=True)
b = torch.tensor([1.123], requires_grad=True)#원하는 실수를 넣어주세요

In [76]:
def linreg(X, w, b):
    """The linear regression model."""
    return torch.matmul(X,w)+b###lr func 코드 완성하기

In [77]:
def squared_loss(y_hat, y):  
    """Squared loss."""
    return (y_hat-y) ** 2###loss function 직접 짜보기

In [93]:
def sgd(params, lr, batch_size):
    """Minibatch stochastic gradient descent."""
    with torch.no_grad():
      for param in params:
            param -= lr * param.grad / batch_size
            param.grad.zero_()
        ###반복문으로 채워넣기

In [96]:
lr = 0.01 ###직접 설정
num_epochs = 100###직접 설정
net = linreg###위에서 가져오기
loss = squared_loss###위에서 가져오기

for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):
        l = loss(net(X,w,b), y)###채워넣기) 
        # Compute gradient on `l` with respect to [`w`, `b`]
        l.sum().backward()
        sgd([w,b],lr,batch_size) 
    with torch.no_grad():
        train_l = loss(net(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')

epoch 1, loss 0.000099
epoch 2, loss 0.000099
epoch 3, loss 0.000099
epoch 4, loss 0.000099
epoch 5, loss 0.000099
epoch 6, loss 0.000099
epoch 7, loss 0.000099
epoch 8, loss 0.000099
epoch 9, loss 0.000099
epoch 10, loss 0.000099
epoch 11, loss 0.000099
epoch 12, loss 0.000099
epoch 13, loss 0.000099
epoch 14, loss 0.000099
epoch 15, loss 0.000099
epoch 16, loss 0.000099
epoch 17, loss 0.000099
epoch 18, loss 0.000099
epoch 19, loss 0.000099
epoch 20, loss 0.000099
epoch 21, loss 0.000099
epoch 22, loss 0.000099
epoch 23, loss 0.000099
epoch 24, loss 0.000099
epoch 25, loss 0.000099
epoch 26, loss 0.000099
epoch 27, loss 0.000099
epoch 28, loss 0.000099
epoch 29, loss 0.000099
epoch 30, loss 0.000099
epoch 31, loss 0.000099
epoch 32, loss 0.000099
epoch 33, loss 0.000099
epoch 34, loss 0.000099
epoch 35, loss 0.000099
epoch 36, loss 0.000099
epoch 37, loss 0.000099
epoch 38, loss 0.000099
epoch 39, loss 0.000099
epoch 40, loss 0.000099
epoch 41, loss 0.000099
epoch 42, loss 0.000099
e

In [97]:
print(f'error in estimating w: {true_w - w.reshape(true_w.shape)}')
print(f'error in estimating b: {true_b - b}')

error in estimating w: tensor([7.5340e-05, 4.6599e-04], grad_fn=<SubBackward0>)
error in estimating b: tensor([-0.0006], grad_fn=<RsubBackward1>)


+cost graph 그리기 (x축 w, y축 loss)

In [98]:
lr = 0.01 ###직접 설정
num_epochs = 100###직접 설정
net = linreg###위에서 가져오기
loss = squared_loss###위에서 가져오기

ww=[]
ll=[]
for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):
        l = loss(net(X,w,b), y)###채워넣기) 
        # Compute gradient on `l` with respect to [`w`, `b`]
        l.sum().backward()
        sgd([w,b],lr,batch_size) 
    with torch.no_grad():
        train_l = loss(net(features, w, b), labels)
        print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')
    ww.append(w)
    ll.append(l.mean())

epoch 1, loss 0.000099
epoch 2, loss 0.000099
epoch 3, loss 0.000099
epoch 4, loss 0.000099
epoch 5, loss 0.000099
epoch 6, loss 0.000099
epoch 7, loss 0.000099
epoch 8, loss 0.000099
epoch 9, loss 0.000099
epoch 10, loss 0.000099
epoch 11, loss 0.000099
epoch 12, loss 0.000099
epoch 13, loss 0.000099
epoch 14, loss 0.000099
epoch 15, loss 0.000099
epoch 16, loss 0.000099
epoch 17, loss 0.000099
epoch 18, loss 0.000099
epoch 19, loss 0.000099
epoch 20, loss 0.000099
epoch 21, loss 0.000099
epoch 22, loss 0.000099
epoch 23, loss 0.000099
epoch 24, loss 0.000099
epoch 25, loss 0.000099
epoch 26, loss 0.000099
epoch 27, loss 0.000099
epoch 28, loss 0.000099
epoch 29, loss 0.000099
epoch 30, loss 0.000099
epoch 31, loss 0.000099
epoch 32, loss 0.000099
epoch 33, loss 0.000099
epoch 34, loss 0.000099
epoch 35, loss 0.000099
epoch 36, loss 0.000099
epoch 37, loss 0.000099
epoch 38, loss 0.000099
epoch 39, loss 0.000099
epoch 40, loss 0.000099
epoch 41, loss 0.000099
epoch 42, loss 0.000099
e

In [99]:
ww

[tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
         [-1.5005]], requires_grad=True), tensor([[ 2.9999],
    

In [91]:
ll

[tensor(8.4864e-05),
 tensor(8.2009e-05),
 tensor(9.8003e-05),
 tensor(9.6190e-05),
 tensor(8.2181e-05),
 tensor(6.9145e-05),
 tensor(9.0845e-05),
 tensor(9.0385e-05),
 tensor(6.4549e-05),
 tensor(0.0001),
 tensor(9.5671e-05),
 tensor(8.1180e-05),
 tensor(0.0001),
 tensor(0.0001),
 tensor(0.0001),
 tensor(5.8518e-05),
 tensor(0.0002),
 tensor(0.0001),
 tensor(0.0001),
 tensor(8.6270e-05),
 tensor(9.1076e-05),
 tensor(6.1275e-05),
 tensor(0.0001),
 tensor(6.3962e-05),
 tensor(8.0033e-05),
 tensor(9.2099e-05),
 tensor(0.0001),
 tensor(7.4771e-05),
 tensor(9.0986e-05),
 tensor(0.0001),
 tensor(0.0001),
 tensor(7.6958e-05),
 tensor(0.0001),
 tensor(5.4825e-05),
 tensor(5.1855e-05),
 tensor(9.5719e-05),
 tensor(7.7488e-05),
 tensor(9.5422e-05),
 tensor(0.0001),
 tensor(9.0725e-05),
 tensor(7.3941e-05),
 tensor(8.8527e-05),
 tensor(0.0001),
 tensor(0.0001),
 tensor(0.0001),
 tensor(9.3564e-05),
 tensor(6.8435e-05),
 tensor(8.6362e-05),
 tensor(0.0001),
 tensor(0.0001),
 tensor(6.8174e-05),
 

In [ ]:
#그래프를 어떻게 그릴지 감이 안 잡히네요 ㅠㅠㅠ 계속 시도해보겠습니당

concise implementation of linear regression 
- api 사용해보기

In [51]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l


true_w = torch.tensor([3, -1.5])
true_b = 5.5
features, labels = d2l.synthetic_data(true_w, true_b, 2000)

In [52]:
def load_array(data_arrays, batch_size, is_train=True): 
    """Construct a PyTorch data iterator."""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 20
data_iter = load_array((features, labels), batch_size)

In [53]:
next(iter(data_iter))

[tensor([[-0.1522, -0.5524],
         [ 1.0293,  0.0681],
         [ 1.0169,  0.6847],
         [ 0.5126,  0.0370],
         [-0.6155,  0.5390],
         [ 0.2803, -0.8995],
         [-0.8118, -0.0488],
         [ 1.4304,  0.2261],
         [-0.2026, -1.1174],
         [-0.8487,  0.8637],
         [ 0.7199, -0.8578],
         [-1.1390, -0.5359],
         [-0.6226,  0.1527],
         [-0.1801,  0.8311],
         [-0.3500, -0.3061],
         [-1.1549, -0.0507],
         [ 0.9090, -0.2768],
         [ 0.9159,  0.8398],
         [ 0.0424, -0.4797],
         [-0.6575,  1.4727]]), tensor([[5.8458],
         [8.4796],
         [7.5257],
         [6.9959],
         [2.8314],
         [7.6988],
         [3.1452],
         [9.4387],
         [6.5767],
         [1.6606],
         [8.9482],
         [2.8865],
         [3.4041],
         [3.7014],
         [4.9069],
         [2.1192],
         [8.6608],
         [6.9854],
         [6.3531],
         [1.3200]])]

In [54]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

In [55]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [56]:
loss = nn.MSELoss()###api function으로 직접 설정

In [57]:
trainer = torch.optim.SGD(net.parameters(), lr=0.01)###api function으로 직접 설정

In [58]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.695363
epoch 2, loss 0.011621
epoch 3, loss 0.000301


In [59]:
w = net[0].weight.data###학습결과 w 구하는 식
print('error in estimating w:', true_w - w.reshape(true_w.shape))
b = net[0].bias.data###학습결과 b 구하는 식
print('error in estimating b:', true_b - b)

error in estimating w: tensor([ 0.0063, -0.0034])
error in estimating b: tensor([0.0122])
